### ISSUE TITLE
key not found: :ciphers (KeyError)

### ISSUE THREAD

**Issue by danielb2** [sosedoff/goodreads#36]
```
/Users/daniel/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)
	from /Users/daniel/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `initialize'
	from /Users/daniel/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `new'
	from /Users/daniel/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/daniel/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /Users/daniel/.rvm/gems/ruby-2.4.2/gems/goodreads-0.4.3/lib/goodreads/request.rb:27:in `request'
	from /Users/daniel/.rvm/gems/ruby-2.4.2/gems/goodreads-0.4.3/lib/goodreads/client/shelves.rb:7:in `shelf'
	from ./export.goodreads.books.rb:10:in `<main>'
```

any idea what could be causing this?

**Comment by danielb2** [comment]
all the test-cases fail due to this as well

**Comment by sosedoff** [comment]
its an issue with rest-client, see https://github.com/rest-client/rest-client/pull/573

btw, i pushed a new version (0.5.0) that should bump the deps and fix your problem.

**Comment by danielb2** [comment]
awesome, thank you
